### ISSUE TITLE
Only this error

### ISSUE THREAD

**Issue by masovskiy** [XaBbl4/pytonconnect#12]
Traceback (most recent call last):
  File "/Users/foxs5local/Downloads/ton-connect-bot-main/src/main.py", line 12, in <module>
    import config
  File "/Users/foxs5local/Downloads/ton-connect-bot-main/src/config.py", line 6, in <module>
    TOKEN = env['my token']
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'my token'

**Comment by XaBbl4** [comment]
The error does not seem to be related with pytonconnect library.

I don’t know where they got this package with the bot, but the bot needs a token from BotFather, which apparently needs to be entered into config.py
